# Generated by Django 3.1.1 on 2020-09-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheets',
            name='liczba',
            field=models.IntegerField(default=0),
        ),
    ]
