# Generated by Django 3.1.1 on 2020-09-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0002_sheets_liczba'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheets',
            options={'verbose_name_plural': 'Arkusze'},
        ),
        migrations.AlterField(
            model_name='sheets',
            name='liczba',
            field=models.CharField(default='Imie', max_length=255, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='sheets',
            name='title',
            field=models.CharField(default='Nazwisko', max_length=255, verbose_name='last_name'),
        ),
    ]
