# Generated by Django 3.1.1 on 2020-09-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0007_auto_20200914_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheets',
            name='x',
        ),
        migrations.AlterField(
            model_name='sheets',
            name='cell2',
            field=models.CharField(default='Sherr', max_length=255, verbose_name='first_name'),
        ),
    ]
