# Generated by Django 3.1.1 on 2020-09-14 07:18

from django.db import migrations, models
import django.db.models.deletion
import gsheets.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0008_auto_20200914_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=127)),
                ('color', models.CharField(max_length=127)),
            ],
            bases=(gsheets.mixins.SheetSyncableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('guid', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('email', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=127, null=True)),
            ],
            bases=(gsheets.mixins.SheetSyncableMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='Sheets',
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='spreadsheet.person'),
        ),
    ]
