# Generated by Django 3.1.1 on 2020-09-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0009_auto_20200914_0918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
