# Generated by Django 3.1.1 on 2020-09-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0011_auto_20200914_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arkusze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=127)),
                ('Nazwisko', models.CharField(max_length=127)),
                ('Email', models.EmailField(max_length=127)),
                ('Numer_telefonu', models.CharField(max_length=127)),
                ('Adres', models.CharField(max_length=127)),
            ],
        ),
        migrations.DeleteModel(
            name='SheetData',
        ),
    ]
