# Generated by Django 3.1.1 on 2020-09-14 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0012_auto_20200914_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaneArkusza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=127)),
                ('Nazwisko', models.CharField(max_length=127)),
                ('Email', models.EmailField(max_length=127)),
                ('Numer_telefonu', models.CharField(max_length=127)),
                ('Adres', models.CharField(max_length=127)),
            ],
            options={
                'verbose_name_plural': 'Arkusze',
            },
        ),
        migrations.RemoveField(
            model_name='arkusze',
            name='Adres',
        ),
        migrations.RemoveField(
            model_name='arkusze',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='arkusze',
            name='Imie',
        ),
        migrations.RemoveField(
            model_name='arkusze',
            name='Nazwisko',
        ),
        migrations.RemoveField(
            model_name='arkusze',
            name='Numer_telefonu',
        ),
        migrations.AddField(
            model_name='arkusze',
            name='Arkusz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='spreadsheet.danearkusza'),
        ),
    ]
