# Generated by Django 3.1.1 on 2020-09-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0014_auto_20200914_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arkusze',
            name='Arkusz',
        ),
        migrations.AddField(
            model_name='arkusze',
            name='Adres',
            field=models.CharField(default=None, max_length=127),
        ),
        migrations.AddField(
            model_name='arkusze',
            name='Email',
            field=models.EmailField(default=None, max_length=127),
        ),
        migrations.AddField(
            model_name='arkusze',
            name='Imie',
            field=models.CharField(default=None, max_length=127),
        ),
        migrations.AddField(
            model_name='arkusze',
            name='Nazwisko',
            field=models.CharField(default=None, max_length=127),
        ),
        migrations.AddField(
            model_name='arkusze',
            name='Numer_telefonu',
            field=models.CharField(default=None, max_length=127),
        ),
        migrations.DeleteModel(
            name='DaneArkusza',
        ),
    ]
