# Generated by Django 3.1.1 on 2020-09-14 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0015_auto_20200914_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arkusze',
            name='id',
        ),
        migrations.AddField(
            model_name='arkusze',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='arkusze',
            name='Email',
            field=models.EmailField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='arkusze',
            name='Numer_telefonu',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
