# Generated by Django 3.1.1 on 2020-09-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0018_auto_20200914_1303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dane_Arkusza',
            new_name='DaneArkusza',
        ),
    ]
