# Generated by Django 3.1.1 on 2020-09-14 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0019_auto_20200914_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danearkusza',
            options={'verbose_name_plural': 'Dane'},
        ),
        migrations.RemoveField(
            model_name='danearkusza',
            name='id',
        ),
        migrations.AddField(
            model_name='danearkusza',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
    ]
