# Generated by Django 3.1.1 on 2020-09-15 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0021_auto_20200915_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='danearkusza',
            options={'verbose_name_plural': 'Arkusz Google'},
        ),
        migrations.AlterField(
            model_name='danearkusza',
            name='guid',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
