# Generated by Django 3.1.1 on 2020-09-22 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0022_auto_20200915_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danearkusza',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
    ]
