# Generated by Django 3.1.1 on 2020-09-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0023_auto_20200922_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danearkusza',
            name='guid',
        ),
        migrations.AddField(
            model_name='danearkusza',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
