# Generated by Django 3.1.1 on 2020-09-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0024_auto_20200925_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danearkusza',
            name='id',
        ),
        migrations.AlterField(
            model_name='danearkusza',
            name='Imie',
            field=models.CharField(max_length=127, primary_key=True, serialize=False),
        ),
    ]
