# Generated by Django 3.1.1 on 2020-09-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0025_auto_20200925_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='danearkusza',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='danearkusza',
            name='Imie',
            field=models.CharField(max_length=127),
        ),
    ]
